In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from catenets.models.jax import *
from catenets.experiment_utils.simulation_utils import simulate_treatment_setup
import numpy as np

In [30]:
X,y,w,p,t = simulate_treatment_setup(100, d=2, n_w=1, n_c=1)

In [31]:
X

array([[ 0.49671415, -1.41537074],
       [-0.1382643 , -0.42064532],
       [ 0.64768854, -0.34271452],
       [ 1.52302986, -0.80227727],
       [-0.23415337, -0.16128571],
       [-0.23413696,  0.40405086],
       [ 1.57921282,  1.8861859 ],
       [ 0.76743473,  0.17457781],
       [-0.46947439,  0.25755039],
       [ 0.54256004, -0.07444592],
       [-0.46341769, -1.91877122],
       [-0.46572975, -0.02651388],
       [ 0.24196227,  0.06023021],
       [-1.91328024,  2.46324211],
       [-1.72491783, -0.19236096],
       [-0.56228753,  0.30154734],
       [-1.01283112, -0.03471177],
       [ 0.31424733, -1.16867804],
       [-0.90802408,  1.14282281],
       [-1.4123037 ,  0.75193303],
       [ 1.46564877,  0.79103195],
       [-0.2257763 , -0.90938745],
       [ 0.0675282 ,  1.40279431],
       [-1.42474819, -1.40185106],
       [-0.54438272,  0.58685709],
       [ 0.11092259,  2.19045563],
       [-1.15099358, -0.99053633],
       [ 0.37569802, -0.56629773],
       [-0.60063869,

In [32]:
y

array([ 1.85148924,  0.76525969,  0.39844511,  0.0209493 , -0.18210917,
       -0.32974384,  2.9683325 ,  0.88007951,  0.42334769, -0.6873674 ,
        4.58128285,  0.30800251,  0.8164898 ,  6.69719055, -0.79199227,
       -0.46925024,  0.74849851,  1.97617862,  1.28514239,  0.68273067,
        1.90339644,  0.23541415,  2.51492926,  1.76299375,  0.12672005,
        5.8968727 ,  1.80657856,  1.13420275,  1.3154092 ,  0.27449158,
        3.08651005, -0.30556588,  1.45265553,  0.09414674,  0.94233689,
        2.99745369, -0.20473496,  2.1961109 , -0.34420712,  0.30083835,
        1.2098489 ,  2.50028487,  3.20812217,  0.66243517,  0.05529229,
       -0.28600737,  1.60585162,  1.06644396,  1.24754273, -0.05885749,
       -0.76275053, -0.20135948,  0.87536508, -0.50978277, -0.73632892,
        0.75398516,  3.7260811 , -0.28242554,  0.94816572,  0.66311258,
       -0.49807998, -0.7879616 ,  0.62389949,  0.46007232,  1.23900113,
        1.64574431,  1.53344253,  3.43788509,  0.04119912, -0.43

In [33]:
p

array([0.63703075, 0.51225127, 0.5335093 , 0.67717453, 0.50505238,
       0.51362645, 0.81949097, 0.53863741, 0.51791348, 0.51873582,
       0.7259379 , 0.5135971 , 0.50388576, 0.91923891, 0.67985077,
       0.52542169, 0.56383916, 0.59052592, 0.63009816, 0.65475374,
       0.66673717, 0.55465329, 0.62083597, 0.73081736, 0.5399617 ,
       0.76898697, 0.64025869, 0.52883311, 0.52315201, 0.52114819,
       0.66633432, 0.70243263, 0.57007762, 0.58316034, 0.59398893,
       0.72575467, 0.54097724, 0.72829864, 0.64713562, 0.59590839,
       0.5372478 , 0.60694707, 0.65686267, 0.50779644, 0.63723692,
       0.57012365, 0.60720027, 0.67156641, 0.52438667, 0.68978784,
       0.51048453, 0.51676339, 0.55728838, 0.5267301 , 0.57131366,
       0.58525776, 0.74007341, 0.51999745, 0.59441201, 0.58557148,
       0.57319606, 0.54078241, 0.65511058, 0.62857478, 0.5979842 ,
       0.62303346, 0.54245803, 0.75973468, 0.51193498, 0.56121005,
       0.55736151, 0.68087062, 0.50045176, 0.65500741, 0.85003

In [34]:
t

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
w

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1])